//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalogo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Catalogo()
        {
            this.Venta_Producto = new HashSet<Venta_Producto>();
        }
    
        public int Id_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public int Id_Categoria { get; set; }
        public decimal Precio_Costo { get; set; }
        public Nullable<decimal> Ganancia { get; set; }
        public decimal Precio_Venta { get; set; }
        public string Unidad { get; set; }
        public string Codigo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Venta_Producto> Venta_Producto { get; set; }
        public virtual Categoria Categoria { get; set; }
        public virtual Inventario Inventario { get; set; }
    }
}
